-- Saltbox Lead Engine — Phase 2A targeted migration: AI-generated business
-- research reports.
--
-- Run this manually in the Supabase SQL editor, AFTER
-- supabase-launch-schema.sql AND supabase-lead-engine-schema.sql have
-- already been applied (this file depends on public.is_admin() and
-- public.set_updated_at() from the former, and public.leads and
-- public.lead_activity_log from the latter).
--
-- This is a targeted addition, not a rerun of supabase-lead-engine-schema.sql
-- — it does not touch public.leads, public.lead_sources,
-- public.outreach_opt_outs, or public.lead_activity_log beyond inserting
-- ordinary rows into lead_activity_log the same way the Netlify Function
-- that owns this feature already does (see netlify/functions/lead-research.js).
-- It creates exactly three new tables for Phase 2A: lead_research_reports,
-- lead_research_sources, lead_asset_candidates.
--
-- Scope: this migration only supports an admin manually triggering AI
-- research for one existing lead at a time from lead-detail.html. It
-- intentionally creates nothing related to scheduled/automatic business
-- discovery, image generation, email sending, automatic outreach, or
-- numeric fit scoring — none of that is part of Phase 2A.
--
-- Write path: lead_research_reports, lead_research_sources, and
-- lead_asset_candidates are never written to directly by the browser.
-- netlify/functions/lead-research.js is the only writer, using
-- SUPABASE_SERVICE_ROLE_KEY (which bypasses RLS entirely, by Supabase's
-- standard service-role behavior) only after it has independently verified
-- the caller's Supabase session and public.is_admin() itself. Admins can
-- SELECT these tables directly from the browser (RLS below), but cannot
-- forge or edit an AI-generated report or source list directly — this is
-- the same "trusted writer, browser reads only" shape
-- supabase-lead-engine-schema.sql already uses for lead_activity_log and
-- outreach_opt_outs. The one browser-writable exception is approving or
-- rejecting a candidate image, which goes through the narrowly-scoped
-- review_lead_asset_candidate() RPC below (same pattern as add_lead_note()
-- in supabase-lead-engine-schema.sql) so a browser session can only ever
-- toggle approved_for_mockup/rejection_reason, never the asset's own facts.
--
-- All actual report writes (create-running / complete / fail) happen through
-- three dedicated, narrowly-scoped RPCs — begin_lead_research_run(),
-- complete_lead_research_run(), fail_lead_research_run() — rather than plain
-- INSERT/UPDATE calls from the Netlify Function. These are NOT admin RPCs:
-- they are revoked from both `public` and `authenticated` and granted only
-- to `service_role`, so they can only ever be called by the trusted
-- Netlify Function itself (which has already independently verified the
-- caller's session and public.is_admin() before ever reaching them) — never
-- directly by a signed-in admin's browser session. See each function's
-- comment below for why this shape exists.
--
-- The whole file runs as one transaction: either every statement below
-- succeeds, or none of it is applied. It is safe to run more than once
-- (every CREATE/ALTER/INDEX/POLICY statement is idempotent).
--
-- Do not run this file until you have reviewed it. Nothing in this
-- repository runs it automatically.

BEGIN;

create extension if not exists pgcrypto;

-- ===========================================================================
-- lead_research_reports
-- One row per AI research run. status='running' rows are how in-flight
-- requests are tracked; the partial unique index below is what actually
-- prevents two concurrent research runs for the same lead (not app-level
-- logic, which could race) — a second INSERT while one is already running
-- fails with a unique-violation that netlify/functions/lead-research.js
-- turns into an HTTP 409.
-- ===========================================================================

create table if not exists public.lead_research_reports (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  status text not null default 'running',

  -- True only for a report generated by the explicit mock-fixture path
  -- (LEAD_RESEARCH_MOCK_MODE=true on the server — see lead-research.js).
  -- Kept as its own boolean rather than inferred from model_used so the UI
  -- has one unambiguous field to key a "MOCK DATA" banner off of, and so a
  -- real and a mock report can never be mistaken for each other.
  is_mock boolean not null default false,

  -- Set only when status='failed'. error_classification is always one of a
  -- fixed, safe set of labels (never a raw provider error) — see the CHECK
  -- constraint below and CLASSIFICATIONS in lead-research.js.
  -- error_message is a short, sanitized, human-readable description written
  -- by the Netlify Function — never the raw OpenAI/Supabase error object,
  -- and never anything that could contain OPENAI_API_KEY or
  -- SUPABASE_SERVICE_ROLE_KEY.
  error_classification text,
  error_message text,

  business_summary text,
  activity_evidence jsonb,
  verified_details jsonb,
  website_findings jsonb,
  brand_cues jsonb,
  recommended_customer_action text,
  personalization_detail text,
  missing_or_conflicting_information jsonb,
  mockup_brief jsonb,
  model_used text,

  -- Trusted actor label captured server-side from the verified caller's
  -- Supabase session (their email, via supabase.auth.getUser()) — mirrors
  -- current_actor_label()'s pattern in supabase-lead-engine-schema.sql, but
  -- computed in the Netlify Function since this row is written with the
  -- service-role key, outside any request.auth.uid() context.
  requested_by_actor text,

  completed_at timestamptz,

  constraint lead_research_reports_status_check check (status in ('running', 'complete', 'failed')),
  constraint lead_research_reports_error_classification_check check (
    error_classification is null or error_classification in (
      'provider_auth_error', 'provider_rate_limited', 'provider_timeout',
      'provider_invalid_response', 'provider_refusal', 'provider_incomplete',
      'provider_unavailable', 'research_validation_failed', 'internal_error'
    )
  ),
  -- Backs the composite foreign keys from lead_research_sources and
  -- lead_asset_candidates below — see "Child-row lead/report consistency".
  constraint lead_research_reports_id_lead_id_unique unique (id, lead_id)
);

-- Enforces "prevent accidental duplicate concurrent runs" at the only place
-- that can actually guarantee it under concurrency: the database. Only one
-- 'running' report may exist per lead at a time.
create unique index if not exists lead_research_reports_one_running_idx
  on public.lead_research_reports (lead_id)
  where status = 'running';

create index if not exists lead_research_reports_lead_id_created_at_idx
  on public.lead_research_reports (lead_id, created_at desc);

drop trigger if exists set_lead_research_reports_updated_at on public.lead_research_reports;
create trigger set_lead_research_reports_updated_at
before update on public.lead_research_reports
for each row execute function public.set_updated_at();

-- ===========================================================================
-- lead_research_sources
-- Every source URL that backs a claim in a specific report. Deliberately a
-- separate table from lead_sources (manual, human-entered source records) —
-- lead_sources is untouched by this file and by lead-research.js. Mixing
-- AI-cited sources into lead_sources would blur "an admin verified and
-- typed this in" with "the model said it found this," which the admin UI
-- needs to keep visually and structurally distinct.
--
-- Child-row lead/report consistency: report_id and lead_id are tied together
-- with a composite foreign key against lead_research_reports(id, lead_id)
-- (backed by that table's own unique(id, lead_id) constraint) instead of two
-- independent single-column foreign keys. This makes it impossible at the
-- database level for a source row's report_id to belong to one lead while
-- its own lead_id names a different one — every write (all of which go
-- through complete_lead_research_run() below) is verified consistent by
-- Postgres itself, not just by application code.
-- ===========================================================================

create table if not exists public.lead_research_sources (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null,
  lead_id uuid not null references public.leads(id) on delete cascade,
  created_at timestamptz not null default now(),

  source_url text not null,
  source_title text,
  source_type text not null default 'other',
  supports_fields jsonb,
  notes text,

  constraint lead_research_sources_source_type_check check (source_type in (
    'business_website', 'social_profile', 'directory_listing', 'review_platform',
    'maps_listing', 'news_or_press', 'other'
  )),
  constraint lead_research_sources_report_lead_fk
    foreign key (report_id, lead_id) references public.lead_research_reports (id, lead_id) on delete cascade
);

create index if not exists lead_research_sources_report_id_idx on public.lead_research_sources (report_id);
create index if not exists lead_research_sources_lead_id_idx on public.lead_research_sources (lead_id);

-- ===========================================================================
-- lead_asset_candidates
-- Candidate images found during research, for admin review only. Nothing in
-- this phase — or this table — ever places one of these into a mockup;
-- approved_for_mockup is only ever a signal for a later phase to read.
-- Same composite-foreign-key consistency guarantee as lead_research_sources
-- above (report_id, lead_id) together must match a real
-- lead_research_reports row.
-- ===========================================================================

create table if not exists public.lead_asset_candidates (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null,
  lead_id uuid not null references public.leads(id) on delete cascade,
  created_at timestamptz not null default now(),

  asset_url text not null,
  source_page_url text not null,
  asset_type text not null default 'other',
  description text,
  ownership_context text,
  approved_for_mockup boolean not null default false,
  rejection_reason text,

  constraint lead_asset_candidates_asset_type_check check (asset_type in (
    'storefront_photo', 'interior_photo', 'service_photo', 'logo',
    'staff_photo', 'menu_or_pricing_board', 'other'
  )),
  constraint lead_asset_candidates_report_lead_fk
    foreign key (report_id, lead_id) references public.lead_research_reports (id, lead_id) on delete cascade
);

create index if not exists lead_asset_candidates_report_id_idx on public.lead_asset_candidates (report_id);
create index if not exists lead_asset_candidates_lead_id_idx on public.lead_asset_candidates (lead_id);

-- ===========================================================================
-- Server-only RPC: begin_lead_research_run
-- Called once per "Run AI Research" click, by the Netlify Function only
-- (after it has already verified the caller's session and public.is_admin()
-- itself — this function does not and cannot re-check is_admin(), since it
-- runs under the service-role connection, which has no auth.uid() at all).
--
-- Atomically:
--   1. verifies the referenced lead actually exists;
--   2. repairs stale 'running' reports for that lead — a Netlify Function
--      invocation can be hard-killed by the platform's own execution-time
--      ceiling before its own catch block ever runs, which would otherwise
--      leave a permanent status='running' row that blocks all future
--      research for that lead forever, since the partial unique index below
--      allows only one running row per lead. A report is considered stale
--      once it has been running for longer than STALE_RUN_THRESHOLD (10
--      minutes, chosen as comfortably longer than any realistic Netlify
--      Function execution ceiling — 10 seconds by default, up to a few
--      minutes for background functions — while still being short enough
--      that a genuinely stuck run does not block research for long);
--   3. inserts the new running report row and returns its id.
--
-- The one-running-report-per-lead invariant (lead_research_reports_one_
-- running_idx) is still the actual concurrency guard: two callers racing
-- here still only ever get one successful INSERT, because the unique index
-- is enforced at the index level regardless of what this function's own
-- SELECT/UPDATE steps observed. A second, near-simultaneous call surfaces a
-- Postgres unique-violation (23505) exactly as it did before this function
-- existed; the Netlify Function still turns that into an HTTP 409.
-- ===========================================================================

create or replace function public.begin_lead_research_run(
  p_lead_id uuid,
  p_requested_by_actor text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_report_id uuid;
  v_stale_threshold constant interval := interval '10 minutes';
begin
  if not exists (select 1 from public.leads where id = p_lead_id) then
    raise exception 'Lead % not found.', p_lead_id;
  end if;

  update public.lead_research_reports
  set status = 'failed',
      error_classification = 'provider_timeout',
      error_message = 'Stale running report automatically marked failed: no completion recorded within the 10-minute staleness threshold (the previous run likely hit a serverless execution time limit).',
      completed_at = now()
  where lead_id = p_lead_id
    and status = 'running'
    and created_at < now() - v_stale_threshold;

  insert into public.lead_research_reports (lead_id, status, requested_by_actor)
  values (p_lead_id, 'running', p_requested_by_actor)
  returning id into v_report_id;

  return v_report_id;
end;
$$;

revoke all on function public.begin_lead_research_run(uuid, text) from public;
revoke all on function public.begin_lead_research_run(uuid, text) from authenticated;
grant execute on function public.begin_lead_research_run(uuid, text) to service_role;

-- ===========================================================================
-- Server-only RPC: complete_lead_research_run
-- Called once, by the Netlify Function only, after it has already validated
-- the research result in full (structure, types, and — for a real OpenAI
-- run — source/citation cross-checking; see lead-research.js). Atomically:
--   1. locks the running report row (FOR UPDATE) and confirms it exists,
--      belongs to the expected lead, and is still 'running' (rejects a
--      double-complete or a complete-after-stale-timeout outright);
--   2. writes the report content and flips status to 'complete';
--   3. inserts the validated source rows (if any);
--   4. inserts the validated asset-candidate rows (if any).
-- Because this is a single function invocation, Postgres itself guarantees
-- all-or-nothing behavior: if any insert fails (e.g. a CHECK constraint
-- rejects a malformed row that somehow slipped past the Netlify Function's
-- own validation), the entire call — including the report-content update —
-- rolls back, so a completed report can never end up with partial or
-- missing child rows. p_lead_id is required and checked against the
-- report's own lead_id so a caller can never complete report A with content
-- while asserting it belongs to lead B. p_sources/p_asset_candidates are
-- each required to be a genuine, non-null JSON array (jsonb_typeof(...) =
-- 'array') before anything else happens — a SQL NULL, JSON null, object,
-- string, or number raises a controlled exception instead of being
-- silently treated as "nothing to insert"; only an actual empty array ([])
-- legitimately results in zero child rows.
-- ===========================================================================

create or replace function public.complete_lead_research_run(
  p_report_id uuid,
  p_lead_id uuid,
  p_business_summary text,
  p_activity_evidence jsonb,
  p_verified_details jsonb,
  p_website_findings jsonb,
  p_brand_cues jsonb,
  p_recommended_customer_action text,
  p_personalization_detail text,
  p_missing_or_conflicting_information jsonb,
  p_mockup_brief jsonb,
  p_model_used text,
  p_is_mock boolean,
  p_sources jsonb,
  p_asset_candidates jsonb
)
returns public.lead_research_reports
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_report public.lead_research_reports;
begin
  select * into v_report from public.lead_research_reports where id = p_report_id for update;

  if v_report.id is null then
    raise exception 'Research report % not found.', p_report_id;
  end if;
  if v_report.lead_id is distinct from p_lead_id then
    raise exception 'Research report % does not belong to lead %.', p_report_id, p_lead_id;
  end if;
  if v_report.status is distinct from 'running' then
    raise exception 'Research report % is not running (status %) and cannot be completed.', p_report_id, v_report.status;
  end if;

  -- Strict input-shape validation: p_sources/p_asset_candidates must each be
  -- a genuine, non-null JSON array. A SQL NULL, a JSON `null`, an object, a
  -- string, a number, or any other JSON type is rejected outright — never
  -- silently treated as "no rows to insert." This is a controlled
  -- exception, not app-level string coercion: the caller (the Netlify
  -- Function) always builds these as real arrays (possibly empty), so
  -- anything else reaching this far indicates a real bug worth surfacing
  -- loudly rather than masking. An empty array ([]) is valid and simply
  -- results in zero child rows below.
  if p_sources is null or jsonb_typeof(p_sources) is distinct from 'array' then
    raise exception 'complete_lead_research_run: p_sources must be a JSON array (got %).', coalesce(jsonb_typeof(p_sources), 'sql null');
  end if;
  if p_asset_candidates is null or jsonb_typeof(p_asset_candidates) is distinct from 'array' then
    raise exception 'complete_lead_research_run: p_asset_candidates must be a JSON array (got %).', coalesce(jsonb_typeof(p_asset_candidates), 'sql null');
  end if;

  if jsonb_array_length(p_sources) > 0 then
    insert into public.lead_research_sources (
      report_id, lead_id, source_url, source_title, source_type, supports_fields, notes
    )
    select
      p_report_id,
      p_lead_id,
      elem ->> 'source_url',
      elem ->> 'source_title',
      coalesce(nullif(elem ->> 'source_type', ''), 'other'),
      elem -> 'supports_fields',
      elem ->> 'notes'
    from jsonb_array_elements(p_sources) as elem;
  end if;

  if jsonb_array_length(p_asset_candidates) > 0 then
    insert into public.lead_asset_candidates (
      report_id, lead_id, asset_url, source_page_url, asset_type, description, ownership_context
    )
    select
      p_report_id,
      p_lead_id,
      elem ->> 'asset_url',
      elem ->> 'source_page_url',
      coalesce(nullif(elem ->> 'asset_type', ''), 'other'),
      elem ->> 'description',
      elem ->> 'ownership_context'
    from jsonb_array_elements(p_asset_candidates) as elem;
  end if;

  update public.lead_research_reports
  set status = 'complete',
      is_mock = p_is_mock,
      error_classification = null,
      error_message = null,
      business_summary = p_business_summary,
      activity_evidence = p_activity_evidence,
      verified_details = p_verified_details,
      website_findings = p_website_findings,
      brand_cues = p_brand_cues,
      recommended_customer_action = p_recommended_customer_action,
      personalization_detail = p_personalization_detail,
      missing_or_conflicting_information = p_missing_or_conflicting_information,
      mockup_brief = p_mockup_brief,
      model_used = p_model_used,
      completed_at = now()
  where id = p_report_id;

  select * into v_report from public.lead_research_reports where id = p_report_id;
  return v_report;
end;
$$;

revoke all on function public.complete_lead_research_run(
  uuid, uuid, text, jsonb, jsonb, jsonb, jsonb, text, text, jsonb, jsonb, text, boolean, jsonb, jsonb
) from public;
revoke all on function public.complete_lead_research_run(
  uuid, uuid, text, jsonb, jsonb, jsonb, jsonb, text, text, jsonb, jsonb, text, boolean, jsonb, jsonb
) from authenticated;
grant execute on function public.complete_lead_research_run(
  uuid, uuid, text, jsonb, jsonb, jsonb, jsonb, text, text, jsonb, jsonb, text, boolean, jsonb, jsonb
) to service_role;

-- ===========================================================================
-- Server-only RPC: fail_lead_research_run
-- The other half of complete_lead_research_run() above — called from the
-- Netlify Function's own catch block when research could not be completed
-- (a classified, sanitized provider/validation/internal error; never a raw
-- error object — see CLASSIFICATIONS in lead-research.js). Only transitions
-- a report that is still 'running' for the expected lead; a report that has
-- already been completed or already failed (e.g. a duplicate/late catch-
-- block invocation) is left untouched rather than overwritten, so a
-- successful completion can never be silently downgraded to failed by a
-- stale error handler.
-- ===========================================================================

create or replace function public.fail_lead_research_run(
  p_report_id uuid,
  p_lead_id uuid,
  p_error_classification text,
  p_error_message text
)
returns public.lead_research_reports
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_report public.lead_research_reports;
begin
  select * into v_report from public.lead_research_reports where id = p_report_id for update;

  if v_report.id is null then
    raise exception 'Research report % not found.', p_report_id;
  end if;
  if v_report.lead_id is distinct from p_lead_id then
    raise exception 'Research report % does not belong to lead %.', p_report_id, p_lead_id;
  end if;

  update public.lead_research_reports
  set status = 'failed',
      error_classification = p_error_classification,
      error_message = p_error_message,
      completed_at = now()
  where id = p_report_id
    and status = 'running';

  select * into v_report from public.lead_research_reports where id = p_report_id;
  return v_report;
end;
$$;

revoke all on function public.fail_lead_research_run(uuid, uuid, text, text) from public;
revoke all on function public.fail_lead_research_run(uuid, uuid, text, text) from authenticated;
grant execute on function public.fail_lead_research_run(uuid, uuid, text, text) to service_role;

-- ===========================================================================
-- Trusted RPC: review_lead_asset_candidate
-- The only way the browser can ever change a lead_asset_candidates row.
-- Narrowly scoped to the two review fields, the same shape as
-- add_lead_note() in supabase-lead-engine-schema.sql — an admin can approve
-- or reject a candidate image, but can never rewrite what it is (asset_url),
-- where it was found (source_page_url), what report/lead it belongs to
-- (report_id/lead_id), or its ownership_context — none of those columns
-- ever appear on the left-hand side of the UPDATE below. Unlike the
-- server-only RPCs above, this one IS meant for direct admin/browser use —
-- it is granted to `authenticated` and itself verifies public.is_admin(),
-- exactly like every other browser-facing RPC in this codebase.
--
-- approved_for_mockup and rejection_reason are always kept internally
-- consistent: approving always clears any prior rejection_reason, and
-- rejecting always stores a non-null reason (falling back to a fixed
-- placeholder if the admin didn't provide one) so a rejected candidate can
-- never be indistinguishable from a never-reviewed one, which previously
-- both had rejection_reason = null.
-- ===========================================================================

create or replace function public.review_lead_asset_candidate(
  p_asset_id uuid,
  p_approved boolean,
  p_rejection_reason text default null
)
returns public.lead_asset_candidates
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.lead_asset_candidates;
begin
  if public.is_admin() is not true then
    raise exception 'Not authorized.';
  end if;

  update public.lead_asset_candidates
  set approved_for_mockup = p_approved,
      rejection_reason = case
        when p_approved then null
        else coalesce(nullif(trim(coalesce(p_rejection_reason, '')), ''), 'Rejected (no reason provided).')
      end
  where id = p_asset_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Asset candidate % not found.', p_asset_id;
  end if;

  return v_row;
end;
$$;

revoke all on function public.review_lead_asset_candidate(uuid, boolean, text) from public;
grant execute on function public.review_lead_asset_candidate(uuid, boolean, text) to authenticated;

-- ===========================================================================
-- Row level security
-- Admins can SELECT all three tables directly from the browser. There is
-- deliberately no browser INSERT/UPDATE/DELETE policy on
-- lead_research_reports, lead_research_sources, or lead_asset_candidates —
-- every write to lead_research_reports/lead_research_sources comes from
-- netlify/functions/lead-research.js via the three service-role-only RPCs
-- above (begin_/complete_/fail_lead_research_run), using
-- SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS by Supabase's standard
-- service-role behavior — and only after that function has independently
-- verified the caller's session and public.is_admin(). lead_asset_candidates
-- is the same, except the narrow review_lead_asset_candidate() RPC above
-- gives admins a single, safe, SECURITY DEFINER write path for
-- approve/reject decisions.
-- ===========================================================================

alter table public.lead_research_reports enable row level security;
alter table public.lead_research_sources enable row level security;
alter table public.lead_asset_candidates enable row level security;

drop policy if exists "Admins can view lead research reports" on public.lead_research_reports;
create policy "Admins can view lead research reports"
on public.lead_research_reports
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can view lead research sources" on public.lead_research_sources;
create policy "Admins can view lead research sources"
on public.lead_research_sources
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can view lead asset candidates" on public.lead_asset_candidates;
create policy "Admins can view lead asset candidates"
on public.lead_asset_candidates
for select
to authenticated
using (public.is_admin());

COMMIT;
